# Generated by Django 4.1.5 on 2023-03-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
