# Generated by Django 4.1.5 on 2023-03-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payslip_deductions_payslip_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='total_payment',
            new_name='total_clock_in_wage',
        ),
    ]
