# Generated by Django 4.1.5 on 2023-03-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_total_payment_payslip_total_clock_in_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='final_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
