# Generated by Django 4.1.5 on 2023-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payslip_total_class_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='payment_confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
