# Generated by Django 4.1.5 on 2023-03-09 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_delete_groupclasspayment'),
        ('payments', '0008_payslip_payslip_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupClassPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendees', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('attendance_logged', models.BooleanField(default=False)),
                ('payment_request_created', models.DateTimeField(auto_now_add=True)),
                ('time_of_payment', models.DateTimeField(blank=True, null=True)),
                ('class_paid_for', models.BooleanField(default=False)),
                ('total_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sent_for_payment', models.BooleanField(default=False)),
                ('payment_for_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.groupclass')),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payslip')),
            ],
        ),
    ]
