# Generated by Django 4.1.5 on 2023-03-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_client_clienttrainerrelationship_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttrainerrelationship',
            name='relationship_level',
            field=models.CharField(choices=[('GLD', 'Gold'), ('SLV', 'Silver'), ('BRZ', 'Bronze')], default='BRZ', max_length=3),
        ),
    ]
