# Generated by Django 4.1.5 on 2023-03-08 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer', '0004_clienttrainerrelationship_relationship_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExerciseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(blank=True, max_length=128, null=True)),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('GRP', 'Group Personal Training'), ('SOLO', 'Solo Personal Training')], max_length=4)),
                ('clients', models.ManyToManyField(to='trainer.client')),
                ('trainer', models.ForeignKey(limit_choices_to={'groups__name': 'Trainer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.client')),
                ('exercises', models.ManyToManyField(to='trainer.sessionexerciseitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainersession')),
            ],
        ),
    ]
