# Generated by Django 4.1.5 on 2023-03-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_sessionexerciseitem_trainersession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('exercises', models.ManyToManyField(to='trainer.sessionexerciseitem')),
            ],
        ),
        migrations.RemoveField(
            model_name='trainersession',
            name='clients',
        ),
        migrations.AddField(
            model_name='trainersession',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainer.client'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TrainingSessionLog',
        ),
        migrations.AddField(
            model_name='sessiondetail',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainersession'),
        ),
    ]
