# Generated by Django 4.1.5 on 2023-03-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_sessiondetail_remove_trainersession_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainersession',
            name='sessions_left',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
