# Generated by Django 4.1.5 on 2023-03-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_groupclass_groupclasspayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupClassPayment',
        ),
    ]
