# Generated by Django 4.1.5 on 2023-03-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_delete_groupclasspayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondetail',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessiondetail',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='trainer.sessionexerciseitem'),
        ),
    ]
