# Generated by Django 4.1.5 on 2023-03-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_alter_sessiondetail_end_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionDetail',
            new_name='SessionExercises',
        ),
    ]
