# Generated by Django 4.1.5 on 2023-02-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_configuration', '0004_customuser_basic_hourly_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='core_colour',
            field=models.CharField(blank=True, default='#876AD7', max_length=7),
        ),
    ]
