# Generated by Django 4.1.5 on 2023-02-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_configuration', '0005_customuser_core_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_preferences',
            field=models.JSONField(null=True),
        ),
    ]
