# Generated by Django 4.1.5 on 2023-02-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_configuration', '0006_customuser_user_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_preferences',
            new_name='preferences',
        ),
    ]
