# Generated by Django 4.1.5 on 2023-02-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_configuration', '0009_alter_customuser_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_per_class_attendee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
