# Generated by Django 4.1.5 on 2023-03-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_configuration', '0010_customuser_payment_per_class_attendee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='payment_per_class_attendee',
            new_name='payment_per_class',
        ),
    ]
