# Generated by Django 4.1.5 on 2023-01-31 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('system_task', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('FR', 'Fresh Tasks'), ('IPR', 'In Progress Tasks'), ('ESC', 'Escalated Tasks'), ('COMP', 'Complete Tasks'), ('ARCH', 'Archived Tasks')], max_length=4)),
                ('priority', models.CharField(blank=True, choices=[('0', 'Low'), ('1', 'Medium'), ('3', 'High')], max_length=1, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
