# Generated by Django 4.1.5 on 2023-01-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_subtask_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='dependencies',
            field=models.ManyToManyField(blank=True, through='tasks.SubTaskDependency', to='tasks.subtask'),
        ),
    ]
