# Generated by Django 4.1.5 on 2023-01-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_subtask_dependencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('FR', 'Fresh Tasks'), ('IPR', 'In Progress Tasks'), ('ESC', 'Escalated Tasks'), ('COMP', 'Complete Tasks'), ('ARCH', 'Archived Tasks')], max_length=4),
        ),
    ]
