# Generated by Django 4.1.5 on 2023-01-31 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_working_on_alter_subtask_subtask_order_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_parent', to='tasks.task'),
        ),
    ]
