# Generated by Django 4.1.5 on 2023-02-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
