# Generated by Django 4.1.5 on 2023-02-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_subtask_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
