# Generated by Django 4.1.5 on 2023-02-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_subtask_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=128),
        ),
    ]
