# Generated by Django 4.1.5 on 2023-01-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0002_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(choices=[('OF', 'Office'), ('MTA', 'Multi-Tasking Area'), ('SA', 'Strength Area'), ('ISMS', 'ISMS Platform'), ('CA', 'Class Area')], max_length=4),
        ),
    ]
