# Generated by Django 4.1.5 on 2023-01-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0003_alter_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_name',
        ),
    ]
