# Generated by Django 4.1.5 on 2023-01-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0004_rename_name_event_event_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location_name',
        ),
    ]
