# Generated by Django 4.1.5 on 2023-01-17 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_schedule', '0005_rename_name_location_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covering', models.BooleanField(default=False)),
                ('covering_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('covering_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_covering_for', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_schedule.event')),
                ('staff_on_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='staff_working',
            field=models.ManyToManyField(through='staff_schedule.EventPersonnel', to=settings.AUTH_USER_MODEL),
        ),
    ]
