# Generated by Django 4.1.5 on 2023-01-17 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_schedule', '0006_eventpersonnel_event_staff_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpersonnel',
            name='covering_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_covering_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
