# Generated by Django 4.1.5 on 2023-01-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0008_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff_schedule.weekday'),
            preserve_default=False,
        ),
    ]
