# Generated by Django 4.1.5 on 2023-01-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0011_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_schedule.shift'),
        ),
    ]
