# Generated by Django 4.1.5 on 2023-01-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0012_clockin_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='time_clocked_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
