# Generated by Django 4.1.5 on 2023-01-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0013_alter_clockin_time_clocked_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_time',
        ),
    ]
