# Generated by Django 4.1.5 on 2023-01-19 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0015_clockin_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 16, 27, 44, 901082, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 16, 27, 48, 389051, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
