# Generated by Django 4.1.5 on 2023-01-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0016_shift_end_time_shift_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='deduction',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
