# Generated by Django 4.1.5 on 2023-01-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0018_clockin_date_to_clock_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='date_to_clock_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
