# Generated by Django 4.1.5 on 2023-01-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0019_alter_clockin_date_to_clock_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='on_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clockin',
            name='status',
            field=models.CharField(choices=[('IA', 'Inactive'), ('EA', 'Early'), ('LTE', 'Late'), ('DSP', 'Disputing'), ('DSPF', 'Dispute Failed'), ('DSPS', 'Dispute Succeeded')], default='IA', max_length=4),
        ),
    ]
