# Generated by Django 4.1.5 on 2023-01-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0020_clockin_on_shift_alter_clockin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clockin',
            name='status',
            field=models.CharField(choices=[('CLSD', 'Closed'), ('EA', 'Early'), ('LTE', 'Late'), ('DSP', 'Disputing'), ('DSPF', 'Dispute Failed'), ('DSPS', 'Dispute Succeeded')], default='CLSD', max_length=4),
        ),
    ]
