# Generated by Django 4.1.5 on 2023-01-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0022_rename_date_to_clock_in_clockin_shift_ends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='paid_for_shift',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
