# Generated by Django 4.1.5 on 2023-01-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0023_clockin_paid_for_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clockin',
            old_name='paid_for_shift',
            new_name='payment_for_shift',
        ),
    ]
