# Generated by Django 4.1.5 on 2023-01-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0024_rename_paid_for_shift_clockin_payment_for_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='payment_for_shift',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
