# Generated by Django 4.1.5 on 2023-02-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0029_alter_shift_shift_weekday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='shift_weekday',
            new_name='weekday',
        ),
    ]
