# Generated by Django 4.1.5 on 2023-02-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0032_alter_shift_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='final_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
