# Generated by Django 4.1.5 on 2023-02-16 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0033_clockin_final_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('clock_in', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='staff_schedule.clockin')),
                ('dispute_status', models.CharField(blank=True, choices=[('FL', 'Failed'), ('PND', 'Pending'), ('SUC', 'Success')], default='PND', max_length=3)),
                ('date_disputed', models.DateTimeField(auto_now_add=True)),
                ('dispute_description', models.TextField(blank=True, max_length=400, null=True)),
                ('dispute_reply', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
