# Generated by Django 4.1.5 on 2023-02-23 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_schedule', '0038_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('attendees_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('payment_per_attendee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000)),
                ('staff_attending', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ISMSSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('CS', 'Classes'), ('MT', 'Meeting'), ('PT', 'Personal Training')], max_length=2)),
                ('schedule_day', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1)),
                ('locations', models.CharField(choices=[('OF', 'Office'), ('MTA', 'Multi-Tasking Area'), ('SA', 'Strength Area'), ('ISMS', 'ISMS Platform'), ('CA', 'Class Area')], max_length=4)),
                ('slug', models.SlugField(blank=True, max_length=12, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_interval', models.CharField(choices=[('DLY', 'Daily'), ('WKLY', 'Weekly'), ('MTH', 'Monthly')], max_length=4)),
                ('recurring_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('group_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_schedule.groupclass')),
                ('staff_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_schedule.meeting')),
            ],
        ),
    ]
