# Generated by Django 4.1.5 on 2023-02-23 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_schedule', '0041_alter_groupclass_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclass',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Trainer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
