# Generated by Django 4.1.5 on 2023-02-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0042_alter_groupclass_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ismsschedule',
            old_name='locations',
            new_name='location',
        ),
    ]
