# Generated by Django 4.1.5 on 2023-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0043_rename_locations_ismsschedule_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ismsschedule',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
