# Generated by Django 4.1.5 on 2023-02-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0044_alter_ismsschedule_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ismsschedule',
            name='schedule_type',
            field=models.CharField(choices=[('CS', 'Class'), ('MT', 'Meeting'), ('PT', 'Personal Training Session')], max_length=2),
        ),
    ]
