# Generated by Django 4.1.5 on 2023-02-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0045_alter_ismsschedule_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclass',
            name='staff_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
            preserve_default=False,
        ),
    ]
