# Generated by Django 4.1.5 on 2023-02-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0046_groupclass_staff_paid_groupclass_total_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclass',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
