# Generated by Django 4.1.5 on 2023-02-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0047_alter_groupclass_total_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupclass',
            name='attendees_count',
        ),
        migrations.RemoveField(
            model_name='groupclass',
            name='payment_per_attendee',
        ),
        migrations.RemoveField(
            model_name='groupclass',
            name='staff_paid',
        ),
        migrations.RemoveField(
            model_name='groupclass',
            name='total_paid',
        ),
    ]
