# Generated by Django 4.1.5 on 2023-02-24 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0049_alter_ismsschedule_slug_groupclasspayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclasspayment',
            name='payment_made',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupclasspayment',
            name='payment_request_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 24, 12, 30, 51, 943987, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupclasspayment',
            name='attendees',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
