# Generated by Django 4.1.5 on 2023-03-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0051_rename_payment_made_groupclasspayment_time_of_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclasspayment',
            name='sent_for_payment',
            field=models.BooleanField(default=False),
        ),
    ]
