# Generated by Django 4.1.5 on 2023-03-05 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('staff_schedule', '0052_groupclasspayment_sent_for_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='payslip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payslip'),
        ),
    ]
