# Generated by Django 4.1.5 on 2023-03-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0054_groupclasspayment_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclasspayment',
            name='attendance_logged',
            field=models.BooleanField(default=False),
        ),
    ]
