# Generated by Django 4.1.5 on 2023-03-08 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_sessionexerciseitem_trainersession_and_more'),
        ('staff_schedule', '0055_groupclasspayment_attendance_logged'),
    ]

    operations = [
        migrations.AddField(
            model_name='ismsschedule',
            name='trainer_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.trainersession'),
        ),
    ]
