# Generated by Django 4.1.5 on 2023-03-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0056_ismsschedule_trainer_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupClassPayment',
        ),
    ]
