# Generated by Django 4.1.5 on 2023-03-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0057_delete_groupclasspayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ismsschedule',
            name='group_class',
        ),
        migrations.DeleteModel(
            name='GroupClass',
        ),
    ]
