# Generated by Django 4.1.5 on 2023-03-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_groupclass_groupclasspayment'),
        ('staff_schedule', '0058_remove_ismsschedule_group_class_delete_groupclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='ismsschedule',
            name='group_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.groupclass'),
        ),
    ]
