# Generated by Django 4.1.5 on 2023-03-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0059_ismsschedule_group_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpersonnel',
            name='covering_for',
        ),
        migrations.RemoveField(
            model_name='eventpersonnel',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventpersonnel',
            name='staff_on_event',
        ),
        migrations.RemoveField(
            model_name='ismsschedule',
            name='trainer_session',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventPersonnel',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
