# Generated by Django 4.1.5 on 2023-03-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_delete_groupclasspayment'),
        ('staff_schedule', '0060_remove_eventpersonnel_covering_for_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ISMSSchedule',
            new_name='ISMSScheduleFixedEvent',
        ),
    ]
