# Generated by Django 4.1.5 on 2023-03-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_alter_sessiondetail_end_time_and_more'),
        ('staff_schedule', '0067_ismsschedulecalendarevent_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ismsschedulecalendarevent',
            name='personal_training_event',
        ),
        migrations.CreateModel(
            name='TrainingSessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_started', models.BooleanField(default=False)),
                ('session_start_time', models.DateTimeField()),
                ('personal_training_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainersession')),
            ],
        ),
    ]
