# Generated by Django 4.1.5 on 2023-03-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0069_ismsschedulecalendarevent_personal_training_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsessioninfo',
            name='session_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
