# Generated by Django 4.1.5 on 2023-03-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0070_alter_trainingsessioninfo_session_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsessioninfo',
            old_name='calendar_Event',
            new_name='calendar_event',
        ),
    ]
