# Generated by Django 4.1.5 on 2023-03-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0071_rename_calendar_event_trainingsessioninfo_calendar_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsessioninfo',
            name='session_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
