# Generated by Django 4.1.5 on 2023-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0072_trainingsessioninfo_session_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ismsschedulecalendarevent',
            name='calendar_event_started',
            field=models.BooleanField(default=False),
        ),
    ]
