# Generated by Django 4.1.5 on 2023-03-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0073_ismsschedulecalendarevent_calendar_event_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ismsschedulecalendarevent',
            old_name='calendar_event_started',
            new_name='started',
        ),
    ]
