# Generated by Django 4.1.5 on 2023-03-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_schedule', '0074_rename_calendar_event_started_ismsschedulecalendarevent_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='ismsschedulecalendarevent',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
