# Generated by Django 4.1.5 on 2023-03-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0012_remove_sessionexercises_end_time_and_more'),
        ('staff_schedule', '0075_ismsschedulecalendarevent_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsessioninfo',
            name='exercises_performed',
            field=models.ManyToManyField(to='trainer.sessionexerciseitem'),
        ),
    ]
